### PR TITLE
feat: add Dockerfile

### LINKED ISSUE #3: master branch not buildable
Hi,

I want to try out this rewrite, but I am unable to setup a working instance. 

There are a bunch of errors in the compose file, the yarn lockfile and some src files

<details><summary>Details</summary>
<p>

But for example the first one when installing the composer dependencies:
`"https://p.yusukekamiyamane.com/icons/downloads/fugue-icons-3.5.6.zip" file could not be downloaded (HTTP/2 404 )`
The URL changed, but there are more errors after fixing this one

</p>
</details> 

Instead of listing all the errors there I would suggest you to try it yourself of the master branch and try to fix the errors

After the master is working I would contribute a installation instructions as well as a Docker image (because Docker images are important I think)

Nice work so far! 👍🏻  (If I would see how it looks^^)

### PR DESCRIPTION
**Pull request by Trickfilm400**
Hi @Lopo,

finally, I got the build process working and here is the result: a Dockerfile for a docker image to run this project in a docker container.

I've also changed the installation instructions, because there were some errors in it, which resulted in installation errors, but the changed documentation works and this is what is used in the Dockerfile

PS: if you don't want the docker instructions in your repository due to limited maintenance time, I can also set up another repo and maintain the docker setup there and we can link to this repo from the offical one

Closes #3 

If you have any questions, feel free to ask

### CODE REVIEW

**Comment by Lopo** [comment]
Hi @Trickfilm400,

sorry for a late response, but last weeks I have so much work , that I barely can do anything else.

For now, I don't have time to fully test your PR, so please set up another repo and I'll put link to it in the README File.

**Comment by Trickfilm400** [comment]
I've created a repository here: https://github.com/Trickfilm400/limas-docker

You can link to this URL I think

I have the issue that after "login" (opening the page) I get the popup to run the setup immediately, but the database migration was directly before, so something is wrong with the code logic? Do you know this issue maybe?

**Comment by Lopo** [comment]
what's the message in popup exactly ?
Isn't it about not running cronjobs ?

**Comment by Trickfilm400** [comment]
Yes, the cronjob warning as well, but I get a browser alert with the following message: `Your database schema is not up-to-date! Please re-run setup immediately!` The database migration ran only seconds before, so this can't be the issue, or do you need to execute another php command maybe?

**Comment by Lopo** [comment]
ah, yeah, I know ... have fix already for it some time, just haven't time to release it, i'll commit it soon

**Comment by Lopo** [comment]
ok, schema problem should be fixed with commit d47da0dab56b65d730702d9007710ece815688a3 and commit 5e1d9af56730867098cfca14d7b9e07f4efb40f0 adds linko to your docker repo

**Comment by Trickfilm400** [comment]
perfect, the error is gone and thank you for the link in the readme (fun fact: if you mention my username with an "@", it's clickable :D and looks better)

> Isn't it about not running cronjobs ?

Just for understanding: do you have this error message as well? Can I fix it or is it also a bug?  

another question: should this PR be open until we merge this sometime in the future or should we close it?

**Comment by Lopo** [comment]
> do you have this error message as well? Can I fix it or is it also a bug?
if u mean that msg about cron, than yes, I have it too
I'm thinking how to solve it ... or "solve" :D

But for now, I think that PR can be closed. I have long time ago started work on docker (compose) , but no time to finish it. Will see if I finish it, or will just use that yours.

**Comment by Trickfilm400** [comment]
> if u mean that msg about cron, than yes, I have it too

okay great, I thought maybe I missed something

> I'm thinking how to solve it ... or "solve" :D

I'm not into the code logic behind this, but for example nextcloud has an PHP file which is executed every 5 minutes via the crontab cronjob (Documentation: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html)

There are 2 real methods:
- executing the file via crontab
- on every page request, via an ajax request some cronjob is started (so every time the browser makes a request to some endpoint and this endpoint checks if something has to be done, just like a dedicated cron.php file via cronjob)

based on the needs either of them can be configured
I think this concept could also be used here?

> I have long time ago started work on docker (compose) , but no time to finish it. Will see if I finish it, or will just use that yours.

I mean it would be interessting to see if we have both the same things done or if one of us has a better implementation, so for me it would be nice to see yours to check, if I could learn some stuff of it, but I know that your time is limited, so yeah, it's also okay if this doesn't happen

I will close this now, but we can still write here (or creating a github discussion or whatever)

**Pull request closed without merging**
